### ISSUE TITLE
Atmega128 or Atmega128A, MegaCore and TV-out.

### ISSUE THREAD

**Issue by curtzan** [Avamander/arduino-tvout#103]
Is it possible? I tried to adding to hardware_setup.h that: 
#elif defined (__AVR_ATmega128__)
//video
#if defined(ENABLE_FAST_OUTPUT)
#define PORT_VID	PORTD
#define	DDR_VID		DDRD
#define	VID_PIN		6
#else
#define PORT_VID	PORTD
#define	DDR_VID		DDRD
#define	VID_PIN		7
#endif
//sync
#define PORT_SYNC	PORTB
#define DDR_SYNC	DDRB
#define SYNC_PIN	5
//sound
#define PORT_SND	PORTB
#define DDR_SND		DDRB
#define	SND_PIN		7

but its not compile. Arduino 1.8.2. Errors like that:
C:\Users\Admin\Documents\Arduino\libraries\TVout\TVout.cpp:97:2: error: 'TIMSK1' was not declared in this scope
  TIMSK1 = 0;

Screenshot of errors:
https://yadi.sk/i/kRFSDJub3HuKGS
What i do wrong?

**Comment by Avamander** [comment]
The compatibility table does not contain your MCU that means you're on your own.
