### ISSUE TITLE
Not compiling examples on Arduino 1.8.2

### ISSUE THREAD

**Issue by ricardojlrufino** [Avamander/arduino-tvout#106]
The examples do not compile giving a linkage error. I had to make the following changes to work.

Rename folder **TVoutfonts** to **utility**
Remove folder TVout (Has a folder inside the other)
Change import to #include <utility/fontALL.h> in sample

**Comment by hafo821** [comment]
Thank´s for this comment... I spent the whole hour of trying to compile these f;king samples

**Comment by allnewmike** [comment]
Me too!

Wish I'd have looked here first.

**Comment by nathantsoi** [comment]
@ricardojlrufino, can you make a PR so we can all use your changes ?

**Comment by ric96** [comment]
@nathantsoi https://github.com/Avamander/arduino-tvout/pull/107

**Comment by treaki** [comment]
i had a similar issue and i solved it by just coping all files from ~/Arduino/libraries/TVout/TVoutfonts to Arduino/libraries/TVout ... Then it worked
