### ISSUE TITLE
please dont render bitmap areas exceeding screen size

### ISSUE THREAD

**Issue by treaki** [Avamander/arduino-tvout#111]
please add a bitmap function that checks if the image size and image position exceeds the screen-size and render only the area that can be displayed at all. I am trying to move a fish over the screen...
See here:
[fishPAL.zip](https://github.com/Avamander/arduino-tvout/files/1287308/fishPAL.zip)

Issues:
if you just put the fish on the screen on a position that exceeds the scree size it will be displayed above that size which results in starting at the other side of the screen.

If you try to put a black box above the the areas you dont want to see the time to render will shourtly flicker a fish that shouldn't be seen. 

see also #110 ; found no possibility to hide the rendering from the user. I guess best would be a blitting system with dubble buffering like in sdl

Thanks in advance

**Comment by Avamander** [comment]
Just pre-cut the bitmap to not include the parts you don't want to be
rendered. I don't have the time to add a function that does it for you
unfortunately.
