### ISSUE TITLE
Fix for opcode error compiler errors

### ISSUE THREAD

**Issue by spaceneedle** [Avamander/arduino-tvout#120]
Hey guys. I have picked up my TVOut project again and i just noticed this. I feel bad abandoning everyone. I have the fix ready for everyone, but for whatever reason, github is not allowing me to submit a pull request to this repo. This library makes use of some assembly macros that break due to something really stupid (I can't remember what triggers it, but it seems that once you get a good project going, it effectively has issues). @Avamander I sent you a direct email containing this fix.

Also, I noticed some issues with the fonts and the examples. It seems like the Arduino IDE can't find them. Either the include is not doing a full search or something else is an issue. Moving them to the root directory fixed the issue.

As I mentioned earlier regarding my project, I am launching a TVOut kit complete with cart slot and two atari compatible joystick ports in September 2019. Its called the Ardu32. The main board is game capable, but when a cart is inserted, it relinquishes the video output to the cartridge and relays game controller input (both digital and analog atari joysticks) via serial. I have a few prototypes here built and they are a lot of fun.

**Comment by LiuTianyouOnLuogu** [comment]
Sorry @spaceneedle  @Avamander , but did you really fix the opcode error?
I can't compile TVout library. Compiler tells me "Opcode Error!!! Macros Error!!!", but I can't understand "asm_marcos.cpp".
Why? I tried it at ATmega320P ATmega2560 etc. But I can't fix it.
Maybe #define in C is good? I don't know.

**Comment by LiuTianyouOnLuogu** [comment]
I am sorry. But it's 10:00 in China. Maybe I need wait for 12 hours.

**Comment by LiuTianyouOnLuogu** [comment]
Guys, How did you define macros?
Why my compiler can't understand?
