### ISSUE TITLE
error: fontALL.h: No such file or directory, Arduino IDE 1.8.15 Library Manager used

### ISSUE THREAD

**Issue by xiaolaba** [Avamander/arduino-tvout#130]
library 1.0.1 and Arduino IDE 1.8.15 are not working together.

opened the Library Manager in the Arduino IDE and install it from there

perhaps author/Arduino.CC is able to help to fix this bug.

workaround as described for ordinary user,
 
goto C:\Users\YOUR_NAME\Documents\Arduino\libraries\TVout\
move folder TVoutfonts to C:\Users\YOUR_NAME\Documents\Arduino\libraries\

**Comment by Avamander** [comment]
Read the second sentence in README.md

**Comment by xiaolaba** [comment]
thx
