### ISSUE TITLE
Max resolution supported ?

### ISSUE THREAD

**Issue by trapdoor26** [Avamander/arduino-tvout#131]
Hello there, 
I am trying to implement a nvr system with OSD (which will be the arduino uno output).
But NVR board only accepts 960H(960x480 (NTSC) / 960x576 (PAL)) resolution as OSD Video input.

When i tried to change the demo code resolution settings to 960H, i got no video on TV(using SCART input of TV).

Sum up, what is the max resolution that we can get from Arduino Uno and how to do it ?

Thanks.

**Comment by waltsatan** [comment]
128x96
