### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by lgcproductions** [Avamander/arduino-tvout#95]
Just installed the library and tried compiling the PAL demo. It's coming up with an error saying the fontsALL.h file is missing. Have checked and it's in the library folder.

Also Sync is on pin 8 for a cloned UNO.

**Comment by Avamander** [comment]
You have failed to install the library correctly. Both font and tvout library have to be directly in the libraries folder. 

If it's a UNO the sync is where UNO's sync is, clones are identical in pinout.

**Comment by lgcproductions** [comment]
So how do I install it correctly then? Ive been doing it via the arduino IDE. Sketch - Include library - Add library .zip.

I got the screen working on the pinout I described  with the R5.91 version of the library.

**Comment by Avamander** [comment]
Open your file explorer and just copy the two libraries (fonts and tvout) from the .zip file into your libraries folder.

**Comment by lgcproductions** [comment]
Ok done that and now i'm getting this error. Just trying to compile the PAL demo example.

https://dl.dropboxusercontent.com/u/4764626/tvout.PNG

**Comment by Avamander** [comment]
You messed up your install somehow. Wipe it and try again.

**Comment by lgcproductions** [comment]
Is that arduino IDE installation or the library? As all the other Library's ive installed work perfectly.

**Comment by abcbarryn** [comment]
What was the first error encountered? What version of the Arduino IDE are you using? Is it the latest version? Please make sure that the TVoutfonts folder is copied up to the library folder, and make sure you are running the current version of the Arduino IDE.

**Comment by lgcproductions** [comment]
Initially it would not compile the newest version of your library saying there was no fontALL.h file found. 
Running IDE 1.6.5. Yup certainly in my library folder as can be seen in the screen grab.

https://dl.dropboxusercontent.com/u/4764626/tvout2.PNG

**Comment by xznhj8129** [comment]
What a mess
